### PR TITLE
WebGPU

### PR DESCRIPTION
**Pull request by Oliver-makes-code**

### CODE REVIEW

**Comment by lucsoft** [comment]
What's the point?

**Comment by lucsoft** [comment]
That comment is not really adding anything it's just the same thing in a different syntax

**Comment by lucsoft** [comment]
@Oliver-makes-code I mean I can merge it but it's really not that useful

**Comment by Oliver-makes-code** [comment]
Merge it

**Review by lucsoft — CHANGES_REQUESTED** [review]
Add more information in comment

**Comment by lucsoft** [comment]
i think this will bloat our game and its not very important for our MVP goal

**Pull request closed without merging**
